language: node_js
node_js: '14'
sudo: true

addons:
  chrome: stable

install:
  - npm ci

script:
  - npm run lint
  - npm run build ngx-matomo-revived
  - npm run test-headless ngx-matomo-revived
  - npm run test-headless demo
